name: FixNotes
version: '1.2.1-SNAPSHOT3'
main: cloud.pg4l.fixNotes.FixNotes
api-version: '1.14'
authors: [ morgus ]
description: Notes that can fix your tools
website: pg4l.cloud
commands:
  fixnote:
    description: Command to use FixNotes
    usage: /fixnote <give/reload> [player]
    permission: fixnotes.use
    permission-message: "You don't have permission to use this command."
